# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97e36571c12bf01c6b24ca5b8a400ca6f5bbcfaa2e208f67f9824e2526e2041d5c2de221a0f709b90938f8390052349f258a58a3b2a1b1ac97a6debc3d038528

test:
  secret_key_base: 5da52a743b606010578f6537afa27c70bebca461e453da625415eb17ea1a90440519b80df55b2fb305aa08f8c4dd19543102148d541c1fdf8242819f7a0d12f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
